api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register("articles", views.ArticleViewSet)
router.register("categories", views.CategoryViewSet)
router.register("products", views.ProductViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('registration/', views.RegistrtionUserView.as_view(), name='registration'),
    path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='my_cart'),
    path('cart/update/', views.UpdateCartView.as_view(), name='update_cart'),
    path('complete_order/', views.CompleteCartView.as_view(), name='complete_order'),
    path('current_user/', views.ProfileView.as_view(), name='current_user'),
    path('current_user/orders/', views.LastOrders.as_view(), name='current_user_orders'),
    path('repeat_order/', views.RepeatOrder.as_view(), name='repeat_order'),

]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('django_rq/', include('django_rq.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.about, name='about'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('create_question', views.create_question, name='create_question'),
    path('create_feedback', views.create_feedback, name='create_feedback')
]

polls/models.py
from django.db import models
from django.db.models import QuerySet, CharField
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', db_index=True)
    publication = models.BooleanField(default=False)
    view_count = models.IntegerField(default=0)
    objects: QuerySet

    def was_published_recently(self) -> int:
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

    def __str__(self) -> CharField:
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    objects: QuerySet

    def __str__(self) -> str:
        return f'{self.question.question_text} - {self.choice_text}'

polls/forms.py
from django import forms
from django.utils import timezone


class QuestionForm(forms.Form):
    question_text = forms.CharField(label='Question', max_length=100)
    publication_date = forms.DateTimeField(initial=timezone.now().date(),
                                           widget=forms.SelectDateWidget())
    choices = forms.CharField(label='Choices', widget=forms.Textarea)


# class FeedbackForm(forms.Form):
#   feedback_text = forms.CharField(label='Inter your feedback', widget=forms.Textarea)

class FeedbackForm(forms.Form):
    feedback_text = forms.CharField(
        label='Share your thoughts about our site:',
        widget=forms.Textarea(attrs={'placeholder': 'We value your feedback!'}),
        required=False,
        max_length=500,
        help_text='Your feedback is important to us. Maximum 500 characters.'
    )

polls/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django_rq import job
from django.db.models import F

from polls.forms import QuestionForm, FeedbackForm
from polls.models import Question, Choice

feedback = []


@job
def get_view_count(question: Question):
    print(f'start {question.view_count}')
    question.view_count = F('view_count') + 1
    question.save()
    print(f'finish {question.view_count}')


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get(self, request, *args, **kwargs):
        question = self.get_object()
        get_view_count.delay(question)
        return super().get(request, *args, **kwargs)


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def about(request: HttpResponse) -> str:
    return render(request, 'polls/about.html')


def vote(request: HttpResponse, question_id: int) -> str:
    question = get_object_or_404(Question, id=question_id)
    try:
        selected_choice = question.choices.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'error_message': "You didn't select a choice",
            'question': question})
    selected_choice.votes += 1
    selected_choice.save()
    return redirect('polls:results', question.id)


def create_question(request: HttpResponse) -> str:
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data['question_text']
            pub_date = form.cleaned_data['publication_date']
            question = Question(question_text=question_text,
                                pub_date=pub_date)
            question.save()
            for choice_text in form.cleaned_data['choices'].split('\n'):
                question.choices.create(choice_text=choice_text, votes=0)
            return redirect('polls:detail', question.id)
    else:
        form = QuestionForm()
        data = {'form': form}
        return render(request, 'polls/create_question.html', context=data)


def create_feedback(request: HttpResponse) -> str:
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback_text = form.cleaned_data['feedback_text']
            feedback.append(feedback_text)
            print(feedback)
            return redirect('polls:index')
    else:
        form = FeedbackForm()
        data = {'form': form}
    return render(request, 'polls/feedback.html', context=data)

polls/templates/polls/about.html
{% extends 'polls/base.html' %}

{% block title%} About site {% endblock %}
{% block body %}
    <h1>About site</h1>
<h3>This site created by Denas Avizhonis.<br>
He doesn't want to be dropped from the course!<br></h3>
А спонсор сайта - туалетная бумага с дырочками.<br>
Туалетная бумага с дырочками - все в твоих руках!<br>
(Типо плохая плогерская шутка)
{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Polls APP {% endblock %}</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'polls:index' %}"> Main page </a> </li>
        <li><a href="{% url 'polls:create_question' %}"> Create new question </a> </li>
        <li><a href="{% url 'polls:about' %}"> About site </a> </li>
        <li><a href="{% url 'polls:create_feedback' %}"> Feedback </a> </li>
        {% if user.is_authenticated %}
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-danger"/>
    </form>
{% else %}
    <li><a href="{% url 'login' %}" class="btn btn-info">Login</a></li>
{% endif %}

    {% for i in menu %}
        <li><a href=" {{i}} "> {{i}} </a></li>
    {% endfor %}
    </ul>

        {% block body %} {% endblock %}

</body>
</html>

polls/templates/polls/create_question.html
{% extends 'polls/base.html' %}

{% block title%} New question {% endblock %}
<body>
    {% block body %}

    <h1>Create your new question:</h1>
    <form action="{% url 'polls:create_question' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create"/>
    </form>

    {% endblock %}
</body>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

    {% block title %} {{question.question_text}} {% endblock %}
<body>
    {% block body %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choices.all|dictsort:'choice_text' %}
            <input type="radio" name="choice" value="{{ choice.id }}"
                id="choice-{{ forloop.counter }}"/>
            <label for="choice-{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote"/>
<h3>{{ question.view_count }}</h3>
</form>
    {% endblock %}
</body>

polls/templates/polls/feedback.html
{% extends 'polls/base.html' %}

{% block title%} Feedback {% endblock %}
<body>
    {% block body %}

    <h1>Create your feedback:</h1>
    <form action="{% url 'polls:create_feedback' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create"/>
    </form>

    {% endblock %}
</body>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

  <title>Polls APP</title>
<body>
    {% block body %}
    <h3>All questions:</h3>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% endblock %}
</body>

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title%} {{question.question_text}} {% endblock %}

    {% block body %}

    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choices.all|dictsort:'choice_text' %}
            <li> {{ choice.choice_text }}-- {{choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    {% endblock %}