api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register("articles", views.ArticleViewSet)
router.register("categories", views.CategoryViewSet)
router.register("products", views.ProductViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('registration/', views.RegistrtionUserView.as_view(), name='registration'),
    path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='my_cart'),
    path('cart/update/', views.UpdateCartView.as_view(), name='update_cart'),
    path('complete_order/', views.CompleteCartView.as_view(), name='complete_order'),
    path('current_user/', views.ProfileView.as_view(), name='current_user'),
    path('current_user/orders/', views.LastOrders.as_view(), name='current_user_orders'),
    path('repeat_order/', views.RepeatOrder.as_view(), name='repeat_order'),

]

articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.show_article, name='show_article'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('login/', views.login, name='login'),
    path('create_article/', views.create_article, name='create_article'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('django_rq/', include('django_rq.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    like_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey('Author', on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Article


def index(request: HttpResponse) -> str:
    articles = Article.objects.all()
    data = {
        'title': 'Main page',
        'articles': articles,
    }
    return render(request, 'articles/index.html', context=data)


def show_article(request: HttpResponse, article_id: int) -> str:
    article = get_object_or_404(Article, pk=article_id)
    data = {'article': article}
    return render(request, 'articles/article.html', context=data)


def like(request: HttpResponse, article_id: int) -> str:
    if request.method == 'POST':
        article = Article.objects.get(id=article_id)
        article.like_count += 1
        article.save()
        return redirect('articles:show_article', article_id)


def about(request: HttpResponse) -> str:
    return render(request, 'articles/about.html')


def feedback(request: HttpResponse) -> str:
    return render(request, 'articles/feedback.html')


def login(request: HttpResponse) -> str:
    return render(request, 'article/login.html')


def create_article(request: HttpResponse) -> str:
    return render(request, 'articles/create_article.html')

articles/templates/articles/about.html
{% extends 'articles/base.html' %}

{% block title%} About site {% endblock %}
{% block content %}
    <h1>About site</h1>
<h3>This site created by Denas Avizhonis.<br>
He doesn't want to be dropped from the course!<br></h3>
А спонсор сайта - туалетная бумага с дырочками.<br>
Туалетная бумага с дырочками - все в твоих руках!<br>
(Типо плохая плогерская шутка)
{% endblock %}

articles/templates/articles/article.html
{% extends 'articles/base.html' %}
{% block content%}
<h1>About {{article.title}}</h1>
<br>
<h3>{{article.content}}</h3>
<p>Author: {{article.author}}</p>
<p>like: {{article.like_count}}</p>
    <form action="{% url 'articles:like' article.id %}" method="post">
            {% csrf_token %}
    <input type="submit" value="Like: {{article.like_count}}"/>
    </form>
{% endblock %}

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if article.title %}
    <title>{{article.title}}</title>
    {% else %}
        <title>{{title}}</title>
    {% endif %}

</head>
<body>
<ul>

    <li><a href="{% url 'articles:index' %}">Main page</a></li>
    <li><a href="{% url 'articles:about' %}">About site</a></li>
    <li><a href="{% url 'articles:create_article' %}">Add new article</a></li>
    <li><a href="{% url 'articles:feedback' %}">Feedback</a></li>
    <li><a href="{% url 'articles:login' %}">Login</a></li>

</ul>

{% block content%} {% endblock %}

</body>
</html>

articles/templates/articles/create_article.html
{% extends 'articles/base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<form action="">
    <p></p><label for="id_1">Text</label><input type="text" id="id_1">
    <p></p><input type="checkbox">
    <p></p><input type="number">
    <p></p><input type="password">
    <p><button type="submit">Send</button> </p>

</form>
    {% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block content%}
<h1> {{title}}</h1>

<ul>
{% for article in articles %}
    <li>
        <h2>{{ article.title }}</h2>
        <p>{{ article.content|truncatewords:20 }}</p>
        <p><a href="{% url 'articles:show_article' article.id %}">Read article</a> </p>
        {% if not forloop.last %}
        <hr>
        {% endif %}
    </li>
{% endfor %}
</ul>
{% endblock %}