api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register("articles", views.ArticleViewSet)
router.register("categories", views.CategoryViewSet)
router.register("products", views.ProductViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('registration/', views.RegistrtionUserView.as_view(), name='registration'),
    path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='my_cart'),
    path('cart/update/', views.UpdateCartView.as_view(), name='update_cart'),
    path('complete_order/', views.CompleteCartView.as_view(), name='complete_order'),
    path('current_user/', views.ProfileView.as_view(), name='current_user'),
    path('current_user/orders/', views.LastOrders.as_view(), name='current_user_orders'),
    path('repeat_order/', views.RepeatOrder.as_view(), name='repeat_order'),

]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('django_rq/', include('django_rq.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('add_product', views.add_product, name='add_product'),
    path('feedback', views.feedback, name='feedback'),
    path('<int:product_id>', views.show_product, name='product'),
    path('<str:category_name>', views.show_category, name='category'),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('my_cart/', views.my_cart, name='my_cart'),
    path('process_order/', views.process_order, name='process_order'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove_entry/', views.remove_entry, name='remove_entry'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('order_history/', views.order_history, name='order_history'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('my_cart/repeat_order/<int:order_id>/', views.repeat_order, name='repeat_order'),
    path('like/<int:product_id>/', views.add_like, name='add_like'),

]

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    category_name = models.CharField(max_length=200)
    objects: QuerySet

    def __str__(self):
        return self.category_name


class Product(models.Model):
    product_name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    sale = models.IntegerField(default=0)
    is_published = models.BooleanField(default=False)
    pub_date = models.DateTimeField('date published')
    likes = models.ManyToManyField(User, through='Like')
    objects: QuerySet

    def __str__(self):
        return self.product_name

    def total_likes(self):
        return self.likes.count()


class OrderEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_entry')
    count = models.IntegerField(default=1, blank=False)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_entries')
    objects: QuerySet

    def __str__(self):
        return f'{self.product} - {self.count}'


class Order(models.Model):
    class Status(models.TextChoices):
        INITIAL = "IN", _("INITIAL")
        COMPLETED = "CP", _("COMPLETED")
        DELIVERED = "DL", _("DELIVERED")

    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.INITIAL)
    objects: QuerySet

    def __str__(self):
        return f"Order: {self.pk} - {self.profile.user.username}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    shopping_cart = models.OneToOneField(Order, on_delete=models.SET_NULL,
                                         null=True, blank=True, related_name='shopping_cart')
    objects: QuerySet

    def __str__(self):
        return f"Profile: {self.user.username}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Product, on_delete=models.CASCADE)


class Comment(models.Model):
    text = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Comment


class RegistrationForm(UserCreationForm):
    """
    Форма для регистрации новых пользователей.

    Attributes:
        first_name (CharField): Поле для ввода имени пользователя (необязательное).
        last_name (CharField): Поле для ввода фамилии пользователя (необязательное).
        email (EmailField): Поле для ввода адреса электронной почты пользователя.

    Meta:
        model (User): Модель, связанная с формой.
        fields (list): Список полей, которые будут отображены в форме регистрации.

    """
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class FeedbackForm(forms.Form):
    feedback_text = forms.CharField(label='Inter your feedback', widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

shop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.cache import cache_page

from shop.forms import UserUpdateForm, FeedbackForm, CommentForm
from shop.models import Product, Category, Order, OrderEntry, Profile, Like, Comment


@cache_page(3)
def index(request: HttpResponse):
    """
    :param request:
    :return: Main page with all category and all products where products==is_published
    """
    products = Product.objects.filter(is_published=True).order_by('category')
    category = Category.objects.all()
    data = {
        'products': products,
        'category': category
    }
    return render(request, 'shop/index.html', context=data)


def show_product(request: HttpResponse, product_id: Product.pk) -> str:
    """
    :param request:
    :param product_id: Product.product.pk
    :return: Page with product.pk
    """
    product = get_object_or_404(Product, pk=product_id)
    likes = Like.objects.filter(post=product).count()
    new_price = 0
    if product.sale != 0:
        new_price: float = product.price / 100 * (100 - product.sale)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            text = form.cleaned_data['text']
            Comment.objects.create(product=product, author=author, text=text)

    comments = Comment.objects.filter(product=product)

    data = {
        'product': product,
        'new_price': round(new_price, 2),
        'sale': product.sale,
        'likes': likes,
        'comments': comments,
        'comment_form': CommentForm()
    }
    return render(request, 'shop/product.html', context=data)


def show_category(request: HttpResponse, category_name: Category.category_name) -> str:
    """
    :param request:
    :param category_name: Category.category_name
    :return: Page with all category on database
    """
    category = get_object_or_404(Category, category_name=category_name)
    products = Product.objects.filter(category_id=category.pk)
    data = {
        'products': products,
        'category': category
    }
    return render(request, 'shop/category.html', context=data)


@login_required
def add_to_cart(request: HttpResponse, product_id: Product.pk) -> str:
    """
    :param request:
    :param product_id: Product.pk
    :return: Add product in shopping cart
    """
    product = get_object_or_404(Product, id=product_id)
    profile = Profile.objects.get(user=request.user)
    if not profile.shopping_cart:
        order = Order.objects.create(profile=profile)
        profile.shopping_cart = order
        profile.save()
    else:
        order = profile.shopping_cart
    order_entry, created = OrderEntry.objects.get_or_create(order=order, product=product)
    if not created:
        order_entry.count += 1
        order_entry.save()
    messages.success(request, f'Product added:  {product.product_name}')
    return redirect('shop:product', product_id=product_id)


@login_required
def my_cart(request: HttpResponse) -> str:
    """
    :param request:
    :return: Page with shopping cart and goods in them
    """
    categories = Category.objects.all()
    profile = Profile.objects.get(user=request.user)
    order: Order = Order.objects.filter(profile=profile, status=Order.Status.INITIAL).first()

    if not order:
        order: Order = Order.objects.create(profile=profile, status=Order.Status.INITIAL)
    order_entry = OrderEntry.objects.filter(order=profile.shopping_cart).order_by('product')
    total_amount = sum(entry.count * entry.product.price for entry in order_entry)
    print(total_amount)
    data = {
        'order': order,
        'total_amount': total_amount,
        'categories': categories,
        'entries': order_entry
    }
    return render(request, 'shop/my_cart.html', context=data)


@login_required
def update_quantity(request: HttpResponse) -> str:
    """
    :param request:
    :return: Updates the amount of product in the user's shopping cart.
    """
    entry_id = request.POST.get('entry_id')
    quantity = request.POST.get('quantity')
    entry = OrderEntry.objects.get(id=entry_id)
    entry.count = quantity
    entry.save()
    return redirect('shop:my_cart')


@login_required
def remove_entry(request: HttpResponse) -> str:
    """
    :param request:
    :return: Removes a product record from the user's shopping cart.
    """
    entry_id = request.POST.get('entry_id')
    entry = OrderEntry.objects.get(id=entry_id)
    entry.delete()
    return redirect('shop:my_cart')


@login_required
def clear_cart(request: HttpResponse) -> str:
    """
    :param request:
    :return: Clears all products from the user's shopping cart.
    """
    profile = Profile.objects.get(user=request.user)
    order = Order.objects.filter(profile=profile, status=Order.Status.INITIAL).first()
    if order:
        OrderEntry.objects.filter(order=profile.shopping_cart).delete()
    return redirect('shop:my_cart')


@login_required
def process_order(request: HttpResponse) -> str:
    """
    :param request:
    :return: Processes the user's order by creating a new order with products from the shopping cart.
    """
    if request.method == 'POST':
        profile = Profile.objects.get(user=request.user)
        order = Order.objects.create(profile=profile, status=Order.Status.COMPLETED)
        if profile.shopping_cart.order_entries.exists():
            entries = profile.shopping_cart.order_entries.all()
            for entry in entries:
                order.order_entries.create(product=entry.product, count=entry.count)
            profile.shopping_cart.order_entries.all().delete()
            data = {
                'order': order
            }
            return render(request, 'shop/order_success.html', context=data)

    return redirect('shop:my_cart')


@login_required
def user_profile(request: HttpResponse) -> str:
    """
    :param request:
    :return: Page with history about user orders.
    """
    categories = Category.objects.all()
    user = request.user
    orders = Order.objects.filter(profile=user.profile).order_by('-id')[:5]
    for order in orders:
        entries = order.order_entries.all()
        total_quantity = sum(entry.count for entry in entries)
        order.total_quantity = total_quantity

        total_amount = sum(entry.product.price * entry.count for entry in entries)
        order.total_amount = total_amount
        order.save()
    data = {
        'user': user,
        'orders': orders,
        'categories': categories
    }
    return render(request, 'shop/user_profile.html', context=data)


@login_required
def order_history(request: HttpResponse) -> str:
    """
    :param request:
    :return: Page with order history with pagination.
    """
    categories = Category.objects.all()
    orders = Order.objects.filter(profile=request.user.profile).order_by('-id')
    paginator = Paginator(orders.all(), 7)
    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)
    for order in orders:
        entries = order.order_entries.all()
        order.total_quantity = sum(entry.count for entry in entries)
        order.total_amount = sum(entry.product.price * entry.count for entry in entries)
        order.product_links = [reverse('shop:product', args=[entry.product.id]) for entry in entries]
    data = {
        'orders': orders,
        'categories': categories
    }
    return render(request, 'shop/order_history.html', context=data)


@login_required
def update_profile(request: HttpResponse) -> str:
    """
    :param request:
    :return: Update user profile and go to page with Profile or page with form for update profile.
    """
    categories = Category.objects.all()
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile has been successfully updated!')
        return redirect('shop:user_profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        data = {
            'user_form': user_form,
            'categories': categories
        }

    return render(request, 'shop/update_user_profile.html', context=data)


@login_required
def repeat_order(request: HttpResponse, order_id: Order.pk):
    """
    :param request:
    :param order_id: Order.pk
    :return: Page with shopping cart.
    """
    order = get_object_or_404(Order, id=order_id, profile=request.user.profile)
    OrderEntry.objects.filter(order=request.user.profile.shopping_cart).delete()
    for entry in order.order_entries.all():
        OrderEntry.objects.create(order=request.user.profile.shopping_cart, product=entry.product, count=entry.count)

    return redirect('shop:my_cart')


def about(request: HttpResponse) -> str:
    """
    :param request:
    :return: Page About site.
    """
    return render(request, 'shop/about.html')


def add_product(request: HttpResponse) -> str:
    products = Product.objects.all().order_by('category')
    category = Category.objects.all()
    data = {
        'products': products,
        'category': category
    }
    return render(request, 'shop/index.html', context=data)


def feedback(request: HttpResponse) -> str:
    """
    :param request:
    :return: Page with feedback about site, feedback print in log.
    """
    user_feedback = []
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():

shop/templates/shop/about.html
{% extends 'shop/base.html' %}

{% block title%} About site {% endblock %}
{% block content %}
    <h1>About site</h1>
<h3>This site created by Denas Avizhonis.<br>
He doesn't want to be dropped from the course!<br></h3>
А спонсор сайта - туалетная бумага с дырочками.<br>
Туалетная бумага с дырочками - все в твоих руках!<br>
(Типо плохая плогерская шутка)
{% endblock %}

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Main page {% endblock %}</title>
    <link type="text/css" href="{% static 'shop/css/style.css' %}" rel="stylesheet"/>


</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<body>
<div class="header">
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
      <button onclick="javascript:history.back()" class="btn btn-outline-success" data-toggle="tooltip" data-placement="top" title="Click to return on last page">Return</button>
      <button class="btn btn-outline-success" type="submit" formaction="{% url 'shop:index' %}" data-toggle="tooltip" data-placement="top" title="Click to return on main page">Main page</button>
      <button class="btn btn-outline-success" type="submit" formaction="{% url 'shop:about' %}" data-toggle="tooltip" data-placement="top" title="Click to visit page about site">About site</button>
      <button class="btn btn-outline-success" type="submit" formaction="{% url 'shop:add_product' %}" data-toggle="tooltip" data-placement="top" title="Click to add new product">Add new product</button>
      <button class="btn btn-outline-success" type="submit" formaction="{% url 'shop:feedback' %}" data-toggle="tooltip" data-placement="top" title="Click to add your feedback">Feedback</button>
      {% if user.is_authenticated %}
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-danger" formaction="{% url 'logout' %}?next={{ request.path }}" formmethod="post" data-toggle="tooltip" data-placement="top" title="Click to logout"/>
        <a class="btn btn-warning m-lg-2 " href="{% url 'shop:my_cart' %}" data-toggle="tooltip" data-placement="top" title="Click to visit page whith your shopping cart">My shopping cart</a>
        <button type="submit" class="btn btn-primary ml-2" formaction="{% url 'shop:user_profile' %}" data-toggle="tooltip" data-placement="top" title="Click to visit your profile">Profile</button>
        <button type="submit" class="btn btn-success" formaction="{% url 'shop:order_history' %}" data-toggle="tooltip" data-placement="top" title="Click to visit page whith history about your orders">Order history</button>
    </form>
      {% else %}
    {% csrf_token %}
    <input type="submit" value="Login" class="btn btn-info" formaction="{% url 'login' %}?next={{ request.path }}" formmethod="post" data-toggle="tooltip" data-placement="top" title="Click to login"/>
{% endif %}
  </form>
</nav>
    </div>


{% block content%} {% endblock %}

<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    </ul>
    <p class="text-center text-body-secondary">Created by: Avizhonis Denas ©</p>
        <p class="text-center text-body-secondary">Не отчисляйте пожалуйста :c</p>

</footer>

</html>

shop/templates/shop/category.html
{% extends 'shop/base.html' %}
{% block title %} {{category}} {% endblock %}
{% block content%}

<h2>All products in category: <a href="{% url 'shop:category' category %}">{{ category|title }}</a></h2>

<ul>
    <li>
        {% for product in products %}
            <h3><a href="{% url 'shop:product' product.id %}"> {{ product.product_name|title }} </a></h3>
            <p>{{ product.description|truncatewords:20 }}</p>
    </li>

{% endfor %}
    <hr>
</ul>
{% endblock %}

shop/templates/shop/feedback.html
{% extends 'shop/base.html' %}

{% block title%} Feedback {% endblock %}
<body>
    {% block content %}

    <h1>Create your feedback</h1>
    <form action="{% url 'shop:feedback' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
         <button type="submit" class="btn btn-primary ml-2">Create</button>
    </form>

    {% endblock %}
</body>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block content%}
<h1> Main page </h1>

<ul>
    {% for cat in category %}
    <li>
        {% if not forloop.first %}
        <hr>
        {% endif %}
        <h2><a href="{% url 'shop:category' cat %}"> {{ cat|title }}</a></h2>
        {% for product in products %}
            {% if cat == product.category %}
            <h3><a href="{% url 'shop:product' product.id %}"> {{ product.product_name|title }} </a></h3>
            <p>{{ product.description|truncatewords:20 }}</p>
        {% endif %}

    </li>

    {% endfor %}
{% endfor %}
    <hr>
</ul>
{% endblock %}

shop/templates/shop/my_cart.html
{% extends 'shop/base.html' %}
{% block title %}Shopping cart{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h2>My shopping cart</h2>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Count</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for entry in entries %}
                <tr>
                    <td>
                        <a href="{% url 'shop:product' entry.product.id %}">{{ entry.product.product_name }}</a>
                    </td>
                    <td>{{ entry.product.price }} руб.</td>
                    <td>
                        <form class="form-inline" action="{% url 'shop:update_quantity' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="entry_id" value="{{ entry.id }}">
                            <input type="number" name="quantity" value="{{ entry.count }}" min="0" class="form-control">
                            <button type="submit" class="btn btn-primary ml-2">Update</button>
                        </form>
                    </td>
                    <td>
                        <form class="form-inline" action="{% url 'shop:remove_entry' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="entry_id" value="{{ entry.id }}">
                            <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <p class="total">Total price: <span id="totalAmount" class="font-weight-bold">{{ total_amount }} руб.</span>
        </p>
        <form class="form-inline" action="{% url 'shop:process_order' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Create order</button>
        </form>
        <form class="form-inline" action="{% url 'shop:clear_cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning">Clear order</button>
        </form>
    </div>
{% endblock %}

shop/templates/shop/order_history.html
{% extends 'shop/base.html' %}

{% block title %}Order history{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Order history</h1>

    <ul class="list-group">
        {% for order in orders %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <span class="fw-bold">Order №{{ order.id }} - Status: {{ order.status }}</span>
                    <div class="product-names mt-2">
                        <ul class="list-unstyled">
                        {% for entry in order.entries.all %}
                            <li>
                                <a href="{% url 'shop:product' entry.product.id %}"
                                   class="text-info text-decoration-none">{{ entry.product.name }}</a>
                                <span class="ml-2 badge bg-warning">Count: {{ entry.count }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                    </div>
                    <span class="badge bg-primary">Total amount: {{ order.total_amount }} руб.</span>
                    <span class="badge bg-secondary">Quantity of goods: {{ order.total_quantity }}</span>

                    <form method="post" action="{% url 'shop:repeat_order' order.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Repeat order</button>
                    </form>
                </div>
            </li>
        {% endfor %}
    </ul>

    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination">
            {% if orders.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ orders.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link">Page {{ orders.number }} of {{ orders.paginator.num_pages }}</span>
            </li>

            {% if orders.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ orders.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ orders.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

shop/templates/shop/order_success.html
{% extends 'shop/base.html' %}
{% block title %}Order successfully placed{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h2>Order successfully placed</h2>
        <p>Your order has been successfully processed. Thank you for your purchase!</p>
    </div>
{% endblock %}

shop/templates/shop/product.html
{% extends 'shop/base.html' %}

{% block title %}
{{ product.product_name }}
{% endblock %}

{% block content %}
<h1>Name: {{ product.product_name|title }}</h1>
<h3>Category: <a href="{% url 'shop:category' product.category %}">{{ product.category|title }}</a></h3>
<h3>Description:</h3>
<div class="centered-text">
    <h3>{{ product.description }}</h3>
</div>

{% if sale != 0%}
    <h4><s>Old price: {{ product.price }} rub.</s></h4>
    <h3>New price: {{ new_price }} rub.</h3>
    <h3>Your discount: {{ sale }}%</h3>
{% else %}
    <h3>Price: {{product.price}} rub.</h3>
{% endif %}

{% if user.is_authenticated %}
 <div>
     <form method="post" action="{% url 'shop:add_to_cart' product.id %}">
         {% csrf_token %}
         <button type="submit" class="btn btn-primary" data-placement="top" title="Click to add to your cart">To cart</button>
     </form>
 </div>
{% endif %}

{% if user.is_authenticated %}
    <form method="post" action="{% url 'shop:add_like' product.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success">Like: {{ likes }}</button>
    </form>
{% endif %}


{% for comment in comments %}
    <div>
        <p>{{ comment.text }}</p>
        <p>{{ comment.author.username }}, {{ comment.created_at }}</p>
    </div>
{% endfor %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить комментарий</button>
</form>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <h3><li>{{ message }}</li></h3>
        {% endfor %}
    </ul>
{% endif %}


{% endblock %}

shop/templates/shop/user_profile.html
{% extends 'shop/base.html' %}

{% block title %}User profile{% endblock %}

{% block content %}
    <div class="container mt-4">
        <ul class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
        <h2 class="mb-4">User information</h2>

        <div class=" justify-content-end mt-4">
            <a href="{% url 'shop:update_profile' %}" class="btn btn-primary mt-4">Change profile</a>
        </div>

        <div class="row mt-4">
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Name:</strong> {{ user.first_name }}</li>
                    <li class="list-group-item"><strong>Surname:</strong> {{ user.last_name }}</li>
                    <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                </ul>
            </div>
        </div>
        <div class=" justify-content-end mt-4">
            <a href="{% url 'shop:order_history' %}" class="btn btn-warning mt-4">All orders</a>
        </div>
        <h3 class="mt-4">Last 5 orders</h3>
        <ul class="list-group">
            {% for order in orders %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>Order №{{ order.id }} - status: {{ order.status }}</span>
                    <ul class="list-unstyled">
                        {% for entry in order.entries.all %}
                            <li>
                                <a href="{% url 'shop:product' entry.product.id %}"
                                   class="text-warning text-decoration-none">{{ entry.product.name }}</a>
                                <span class="ml-2 badge bg-primary"> Count: {{ entry.count }}</span>
                            </li>
                        {% endfor %}
                    </ul>

                    <span class="">Total amount: {{ order.total_amount }} руб.</span>
                    <span class="badge bg-dark">Quantity of products: {{ order.total_quantity }}</span>

                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}